In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import accuracy_score

from scipy.stats import entropy


# import some data to play with
iris = datasets.load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.33, random_state=42)

# def change_weights(X_train,y_train,X_test,y_test,weights):

In [2]:
pk = np.array([1/5, 2/5, 2/5])  # fair coin
H = entropy(pk)
print(H)

1.0549201679861442


In [3]:
H=-0.2*(np.log(0.2))-0.4*(np.log(0.4))-0.4*(np.log(0.4))
print(H)

1.0549201679861442


In [6]:
def calculate_probabilities(list_labels,uniq_labels):
    '''
    this function calculates the probabilities of each label in the list of labels
    it is calculated by number of labels in class A/all labels
    number of labels in class B/all labels
    and so on
    '''
    
    # put your code here
    # Code by Momin
    count_labels = [0 for i in range(len(uniq_labels))]
    for i in range(len(uniq_labels)):
        count_labels[i] = list_labels.count(uniq_labels[i])
    probabilities = [count/len(list_labels) for count in count_labels]
    return probabilities
    
    
# test your function
list_labels=[1,2,0,1,2,0]
uniq_labels=[0,1,2]
print(calculate_probabilities(list_labels,uniq_labels))
# this should print somehting like 0.33,0.33,0.33

[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]


In [14]:
import math

def calc_entropy_from_probabilities(list_probas):
    '''
    list_probas is the list of probabiities
    the formula for entropy is
    sum(-proba*log(proba))
    '''
    # for now returning the same list
    # put your code to calculate entropy
    # Code by Momin

    entropy = 0

    for proba in list_probas:
      entropy = entropy - (proba*(np.log(proba)))
    
    return entropy

# test your function
list_probas=[1/5, 2/5, 2/5]
print(calc_entropy_from_probabilities(list_probas))
# above should print 1.054...

1.0549201679861442


In [23]:
import numpy as np

def information_gain(old_entropy,new_entropies,count_items):
    '''
    from the list of new entropies, calculate the overall new entropy
    
    formula is something like:
    overall_new_entropy = entropy1*proportion1 + entropy2*proportion2+ entropy3*proportion3 ...
    
    igain=old_entropy-overall_new_entropy
    '''
    # Code by Momin

    overall_new_entropy = 0
    for entropy, count in zip(new_entropies, count_items):
        proportion = count/sum(count_items)
        overall_new_entropy += entropy * proportion
    igain = old_entropy - overall_new_entropy
    
    return igain


#test your function
old_entropy=1
new_entropies=[0,0.65]
count_items=[4,6]
print(information_gain(old_entropy,new_entropies,count_items))
# above should print 0.61

0.61


In [16]:
num_feats=X_train.shape[1]
def initialize_weights(number_features):
    '''
    the first set of weights corresponding to the features
    defaults to 1
    '''
    
    weights=np.array([2 for i in range(number_features)])
    return weights

print(initialize_weights(num_feats))    

[2 2 2 2]


In [17]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [18]:
def change_weights(weights):
    new_weights=[]
    for i in range(weights[-1].shape[0]):
        new_weights.append(np.random.uniform(0,1))
    return np.array(new_weights)

In [19]:
def apply_and_measure_accuracy(X,y,weights):    
    res=np.sum(X*weights[-1],axis=1)
    res = np.tanh(res)
    res[res>0.5]=1
    res[res<=0.5]=0
    acc=accuracy_score(y, res)
    return acc
    
def get_train_test_accuracy(X_train,y_train,X_test,y_test,weights):
    train_acc=apply_and_measure_accuracy(X_train,y_train,weights)
    test_acc=apply_and_measure_accuracy(X_test,y_test,weights)
    return train_acc,test_acc

In [20]:
wt_init=[initialize_weights(num_feats)]
res=np.sum(X_test*wt_init[-1],axis=1)
res = np.tanh(res)
res[res>0.5]=1
res[res<=0.5]=0
print(res.shape)
acc=accuracy_score(y_test, res)
test_accuracies=[acc]

res=np.sum(X_train*wt_init[-1],axis=1)
res = np.tanh(res)
res[res>0.5]=1
res[res<=0.5]=0
print(res.shape)
acc=accuracy_score(y_train, res)

train_accuracies=[acc]
print("Initial test acc",test_accuracies)




def train_weights(X_train,y_train,X_test,y_test,weights,train_accuracies,test_accuracies):
    print("Trial number ",len(weights))
    
    train_acc,test_acc=get_train_test_accuracy(X_train,y_train,X_test,y_test,weights)
    
    
    
    # store the accuracy in this list of accuracies
    train_accuracies.append(train_acc)
    test_accuracies.append(test_acc)
    print("train",train_acc,"test",test_acc)
    print(test_accuracies[-1],test_accuracies[-2])
    
    # exit condition
    if test_accuracies[-1]<test_accuracies[-2]:
        print("returning")
        return weights,train_accuracies,test_accuracies
    
    # change the weights according to the accuracy
    new_weights=change_weights(weights)
    weights.append(new_weights)
    return train_weights(X_train,y_train,X_test,y_test,weights,train_accuracies,test_accuracies)

(50,)
(100,)
Initial test acc [0.3]


In [21]:
weights,train_accuracies,test_accuracies=train_weights(X_train,y_train,X_test,y_test,wt_init,train_accuracies,test_accuracies)

Trial number  1
train 0.35 test 0.3
0.3 0.3
Trial number  2
train 0.35 test 0.3
0.3 0.3
Trial number  3
train 0.35 test 0.3
0.3 0.3
Trial number  4
train 0.35 test 0.3
0.3 0.3
Trial number  5
train 0.35 test 0.3
0.3 0.3
Trial number  6
train 0.35 test 0.3
0.3 0.3
Trial number  7
train 0.35 test 0.3
0.3 0.3
Trial number  8
train 0.35 test 0.3
0.3 0.3
Trial number  9
train 0.35 test 0.3
0.3 0.3
Trial number  10
train 0.35 test 0.3
0.3 0.3
Trial number  11
train 0.35 test 0.3
0.3 0.3
Trial number  12
train 0.35 test 0.3
0.3 0.3
Trial number  13
train 0.35 test 0.3
0.3 0.3
Trial number  14
train 0.35 test 0.3
0.3 0.3
Trial number  15
train 0.35 test 0.3
0.3 0.3
Trial number  16
train 0.35 test 0.3
0.3 0.3
Trial number  17
train 0.35 test 0.3
0.3 0.3
Trial number  18
train 0.35 test 0.3
0.3 0.3
Trial number  19
train 0.35 test 0.3
0.3 0.3
Trial number  20
train 0.35 test 0.3
0.3 0.3
Trial number  21
train 0.35 test 0.3
0.3 0.3
Trial number  22
train 0.35 test 0.3
0.3 0.3
Trial number  23
tr

In [22]:
### Test the weights in the pre-final iteration
res=np.sum(X_test*weights[-2],axis=1)
res = np.tanh(res)
res[res>0.5]=1
res[res<=0.5]=0
acc=accuracy_score(y_test, res)
print(acc)
print(res)

0.34
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


In [24]:
# step 1: calculate the probabilities of 0, 1, and 2 in the y_test array
labels, counts = np.unique(y_test, return_counts=True)
proba_init = dict(zip(labels, counts / len(y_test)))
print("Initial proba=", proba_init)

# step 2: calculate the initial entropy of y_test, using the probability values
# convert the dictionary to a list and get only the probability values
list_probas = [proba for proba in proba_init.values()]
print(list_probas)
entropy_init = calc_entropy_from_probabilities(list_probas)
print("Initial entropy = ", entropy_init)


Initial proba= {0: 0.38, 1: 0.3, 2: 0.32}
[0.38, 0.3, 0.32]
Initial entropy =  1.0934927418975058


In [26]:
wt_init = initialize_weights(num_feats)
print(wt_init)

res = np.sum(X_test * wt_init, axis=1)
print(res)

[2 2 2 2]
[29.6 23.  39.  29.8 31.6 21.4 26.8 34.8 28.8 27.2 33.6 18.6 21.  19.2
 21.4 31.8 35.  26.2 28.6 34.  19.4 31.6 20.8 33.8 40.2 34.4 33.6 36.4
 19.  19.4 18.8 24.  31.2 20.  18.2 31.4 31.2 20.8 20.4 21.8 31.  31.
 32.  22.  21.6 25.2 31.4 33.6 30.8 38.8]


In [29]:
# choose a threshold between minimum and maximum of res
threshold = np.random.uniform(np.min(res), np.max(res))
print(threshold)

# make two groups
group1=[]
group2=[]

for i in range(res.shape[0]):
    if res[i]<threshold:
        group1.append(y_test[i])
    else:
        group2.append(y_test[i])
    

38.390482891688876


In [33]:
from collections import Counter

# Calculate probabilities of items in group 1
counts_gr1 = Counter(group1)
total_gr1 = len(group1)
proba_gr1 = {k: v/total_gr1 for k, v in counts_gr1.items()}

# Convert the dictionary into a list
proba_gr1 = [v for k, v in proba_gr1.items()]

# Calculate entropy for group 1
entropy_group1 = np.sum(-proba * np.log(proba) for proba in proba_gr1)

# Calculate probabilities of items in group 2
counts_gr2 = Counter(group2)
total_gr2 = len(group2)
proba_gr2 = {k: v/total_gr2 for k, v in counts_gr2.items()}

# Convert the dictionary into a list
proba_gr2 = [v for k, v in proba_gr2.items()]

# Calculate entropy for group 2
entropy_group2 = np.sum(-proba * np.log2(proba) for proba in proba_gr2)

new_entropies=[entropy_group1,entropy_group2]
count_items=[total_gr1,total_gr2]
ig=information_gain(entropy_init,new_entropies,count_items)
print("IG=",ig)

IG= 0.0725427016439606


<ipython-input-33-bd1d6057da4d>:12: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  entropy_group1 = np.sum(-proba * np.log(proba) for proba in proba_gr1)
<ipython-input-33-bd1d6057da4d>:23: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  entropy_group2 = np.sum(-proba * np.log2(proba) for proba in proba_gr2)


In [34]:
def change_weights(weights):
    new_weights=[]
    for i in range(weights[-1].shape[0]):
        new_weights.append(np.random.uniform(0,1))
    return np.array(new_weights)

def apply_and_measure_accuracy(X,y,weights):    
    res=np.sum(X*weights[-1],axis=1)
    res = np.tanh(res)
    res[res>0.5]=1
    res[res<=0.5]=0
    acc=accuracy_score(y, res)
    return acc
    
def get_train_test_accuracy(X_train,y_train,X_test,y_test,weights):
    train_acc=apply_and_measure_accuracy(X_train,y_train,weights)
    test_acc=apply_and_measure_accuracy(X_test,y_test,weights)
    return train_acc,test_acc    

In [35]:
wt_init=[initialize_weights(num_feats)]
res=np.sum(X_test*wt_init[-1],axis=1)
res = np.tanh(res)
res[res>0.5]=1
res[res<=0.5]=0
print(res.shape)
acc=accuracy_score(y_test, res)
test_accuracies=[acc]

res=np.sum(X_train*wt_init[-1],axis=1)
res = np.tanh(res)
res[res>0.5]=1
res[res<=0.5]=0
print(res.shape)
acc=accuracy_score(y_train, res)

train_accuracies=[acc]
print("Initial test acc",test_accuracies)




def train_weights(X_train,y_train,X_test,y_test,weights,train_accuracies,test_accuracies):
    print("Trial number ",len(weights))
    
    train_acc,test_acc=get_train_test_accuracy(X_train,y_train,X_test,y_test,weights)
    
    
    
    # store the accuracy in this list of accuracies
    train_accuracies.append(train_acc)
    test_accuracies.append(test_acc)
    print("train",train_acc,"test",test_acc)
    print(test_accuracies[-1],test_accuracies[-2])
    
    # exit condition
    if test_accuracies[-1]<test_accuracies[-2]:
        print("returning")
        return weights,train_accuracies,test_accuracies
    
    # change the weights according to the accuracy
    new_weights=change_weights(weights)
    weights.append(new_weights)
    return train_weights(X_train,y_train,X_test,y_test,weights,train_accuracies,test_accuracies)

(50,)
(100,)
Initial test acc [0.3]


In [37]:
weights,train_accuracies,test_accuracies=train_weights(X_train,y_train,X_test,y_test,wt_init,train_accuracies,test_accuracies)

Trial number  949
train 0.35 test 0.3
0.3 0.3
Trial number  950
train 0.35 test 0.3
0.3 0.3
Trial number  951
train 0.35 test 0.3
0.3 0.3
Trial number  952
train 0.35 test 0.3
0.3 0.3
Trial number  953
train 0.35 test 0.3
0.3 0.3
Trial number  954
train 0.35 test 0.3
0.3 0.3
Trial number  955
train 0.35 test 0.3
0.3 0.3
Trial number  956
train 0.35 test 0.3
0.3 0.3
Trial number  957
train 0.35 test 0.3
0.3 0.3
Trial number  958
train 0.35 test 0.3
0.3 0.3
Trial number  959
train 0.35 test 0.3
0.3 0.3
Trial number  960
train 0.35 test 0.3
0.3 0.3
Trial number  961
train 0.35 test 0.3
0.3 0.3
Trial number  962
train 0.35 test 0.3
0.3 0.3
Trial number  963
train 0.35 test 0.3
0.3 0.3
Trial number  964
train 0.35 test 0.3
0.3 0.3
Trial number  965
train 0.35 test 0.3
0.3 0.3
Trial number  966
train 0.35 test 0.3
0.3 0.3
Trial number  967
train 0.35 test 0.3
0.3 0.3
Trial number  968
train 0.35 test 0.3
0.3 0.3
Trial number  969
train 0.35 test 0.3
0.3 0.3
Trial number  970
train 0.35 test 

In [38]:
### Test the weights in the pre-final iteration
res=np.sum(X_test*weights[-2],axis=1)
res = np.tanh(res)
res[res>0.5]=1
res[res<=0.5]=0
acc=accuracy_score(y_test, res)
print(acc)
print(res)

0.44
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]
