In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import accuracy_score

from scipy.stats import entropy


# import some data to play with
iris = datasets.load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.33, random_state=42)

# def change_weights(X_train,y_train,X_test,y_test,weights):

In [2]:
pk = np.array([1/5, 2/5, 2/5])  # fair coin
H = entropy(pk)
print(H)


1.0549201679861442


In [3]:
H=-0.2*(np.log(0.2))-0.4*(np.log(0.4))-0.4*(np.log(0.4))
print(H)


1.0549201679861442


In [4]:
def calculate_probabilities(list_labels,uniq_labels):
    '''
    this function calculates the probabilities of each label in the list of labels
    it is calculated by number of labels in class A/all labels
    number of labels in class B/all labels
    and so on
    '''
    
    # put your code here
    probabilities = {}
    total = len(list_labels)
    for label in uniq_labels:
        count = list_labels.count(label)
        probability = count / total
        probabilities[label] = probability
    return probabilities
    



    
    
    
# test your function
list_labels=[1,2,0,1,2,0]
uniq_labels=[0,1,2]
print(calculate_probabilities(list_labels,uniq_labels))
# this should print somehting like 0.33,0.33,0.33


{0: 0.3333333333333333, 1: 0.3333333333333333, 2: 0.3333333333333333}


In [5]:
import math
def calc_entropy_from_probabilities(list_probas):
    '''
    list_probas is the list of probabiities
    the formula for entropy is
    sum(-proba*log(proba))
    
    '''
    
    # for now returning the same list
    # put your code to calculate entropy
    entropy_value = 0
    for proba in list_probas:
        if proba > 0:
            entropy_value += -proba * np.log(proba)
    return entropy_value
    return list_proba

# test your function
list_probas=[1/5, 2/5, 2/5]
print(calc_entropy_from_probabilities(list_probas))
# above should print 1.054...


1.0549201679861442


In [6]:
def information_gain(old_entropy,new_entropies,count_items):
    '''
    from the list of new entropies, calculate the overall new entropy
    
    formula is something like:
    overall_new_entropy = entropy1*proportion1 + entropy2*proportion2+ entropy3*proportion3 ...
    
    igain=old_entropy-overall_new_entropy
    '''
    
    overall_entropy = 0 
    numberOfItems = sum (count_items) # will be 10 (4+6)
    for i in range(len(new_entropies)):
        ratios = count_items[i]/numberOfItems
        overall_entropy += new_entropies[i] * ratios
        
    
    
    igain = old_entropy - overall_entropy    
    return igain


#test your function
old_entropy=1
new_entropies=[0,0.65]
count_items=[4,6]
print(information_gain(old_entropy,new_entropies,count_items))
# above should print 0.61
    

0.61


In [7]:
num_feats=X_train.shape[1]
def initialize_weights(number_features):
    '''
    the first set of weights corresponding to the features
    defaults to 1
    '''
    
    weights=np.array([2 for i in range(number_features)])
    return weights


In [8]:
print(initialize_weights(num_feats))


[2 2 2 2]


In [9]:
y_test


array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

# Task 2: Iteration



In [15]:
 # initialization
#Author: Abdul-Rahman Abdel-Fattah
# step 1 calculate the probabilities of 0, 1 and 2 in the y_test array
proba_init= calculate_probabilities(y_test.tolist(),np.unique(y_test).tolist())        #get the probabilities for y_test
print("Initial proba=",proba_init)

# step 2 calculate the initial entropy of y_test, using the probability values
# you might have to convert the dictionary to a list
# get only the probability values
list_probas= list(proba_init.values()) #get list from dictionary proba_init
print(list_probas)
entropy_init= calc_entropy_from_probabilities(list_probas)
print("Initial entropy = ",entropy_init)

Initial proba= {0: 0.38, 1: 0.3, 2: 0.32}
[0.38, 0.3, 0.32]
Initial entropy =  1.0934927418975058


In [21]:
#Author: Abdul-Rahman Abdel-Fattah
wt_init=initialize_weights(num_feats)
# right now the initialize_weights function only returns 2,2,2 
print(wt_init)

# multiply the weights with each feature and calculate the sum
res= np.sum( wt_init * X_test , axis =1)# use np.sum() function
print(res)

[2 2 2 2]
[29.6 23.  39.  29.8 31.6 21.4 26.8 34.8 28.8 27.2 33.6 18.6 21.  19.2
 21.4 31.8 35.  26.2 28.6 34.  19.4 31.6 20.8 33.8 40.2 34.4 33.6 36.4
 19.  19.4 18.8 24.  31.2 20.  18.2 31.4 31.2 20.8 20.4 21.8 31.  31.
 32.  22.  21.6 25.2 31.4 33.6 30.8 38.8]


In [33]:
#Author: Abdul-Rahman Abdel-Fattah
# choose a threshold between res.minimum and res.maximum

threshold=np.random.uniform(res.min(), res.max())
# use np.random.uniform() function
print(threshold)

# make two groups
group1=[]
group2=[]

##place the element in a group depending if greater/smaller than threshold
for i in range(res.shape[0]):
    if res[i]<threshold:
        group1.append(y_test[i]).append(y_test[i])
    else:
        group2.append(y_test[i])

18.252172271539482


AttributeError: 'NoneType' object has no attribute 'append'

In [34]:
#Author: Abdul-Rahman Abdel-Fattah
##generating the probabilities of group 1
## calculate entropy of 
proba_gr1=calculate_probabilities(group1,np.unique(group1).tolist())
proba_gr1=list(proba_gr1.values()) 
entropy_group1=calc_entropy_from_probabilities(proba_gr1)
count_group1=len(proba_gr1)

proba_gr2=calculate_probabilities(group2,np.unique(group2).tolist())
proba_gr2=list(proba_gr2.values()) 
entropy_group2=calc_entropy_from_probabilities(proba_gr2)
count_group2=len(proba_gr2)

new_entropies=[entropy_group1,entropy_group2]
count_items=[count_group1,count_group2]
ig=information_gain(entropy_init,new_entropies,count_items)
print("Info Gain =",ig)

IG= 0.27402471412044016
